aws_region         = "us-west-1"
key_name           = "natalie_key2"
instance_type      = "t3.medium"
ami_id             = "ami-014e30c8a36252ae5"
availability_zones = ["us-west-1a", "us-west-1b"]
public_subnets     = ["10.0.1.0/24"]
desired_capacity   = 2
min_size           = 1
max_size           = 4