apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  namespace: dev
  labels:
    app: yolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: nataliea7/yolo-image:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: yolo-env-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
