apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yolo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolo
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
  namespace: dev
spec:
  selector:
    app: yolo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080