#name: Deploy Nginx Dev Config
#
#on:
#  push:
#    branches:
#      - dev
#
#jobs:
#  deploy-nginx-dev:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      # ✅ Copy config file (already there)
#      - name: Copy config to home folder on EC2
#        uses: appleboy/scp-action@v0.1.3
#        with:
#          host: ${{ secrets.NGINX_DEV_HOST }}
#          username: ubuntu
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          source: "nginx-config/default.conf"
#          target: "~/conf.d"
#          overwrite: true
#
#      # ✅ Copy the shell script
#      - name: Copy script to EC2
#        uses: appleboy/scp-action@v0.1.3
#        with:
#          host: ${{ secrets.NGINX_DEV_HOST }}
#          username: ubuntu
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          source: "deploy_nginx_container.sh"
#          target: "/home/ubuntu/"
#          overwrite: true
#
#      # ✅ Run the script remotely via SSH
#      - name: Run Nginx Docker Script
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.NGINX_DEV_HOST }}
#          username: ubuntu
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            chmod +x /home/ubuntu/deploy_nginx_container.sh
#            bash /home/ubuntu/deploy_nginx_container.sh