name: Provision Kubernetes Cluster Infrastructure

on:
  push:
    branches:
      - main

jobs:
  provision-infra:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      working-directory: tf
      run: terraform init

    - name: Select or Create Workspace
      working-directory: tf
      run: terraform workspace select us-west-1 || terraform workspace new us-west-1

    - name: Terraform Apply
      working-directory: tf
      run: terraform apply -var-file=region.us-west-1.tfvars -auto-approve
