name: Provision Kubernetes Cluster Infrastructure

on:
  push:
    branches:
      - main

jobs:
  provision-infra:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      working-directory: tf
      run: terraform init

    - name: Select or Create Workspace
      working-directory: tf
      run: terraform workspace select us-west-1 || terraform workspace new us-west-1

    - name: Terraform Apply
      working-directory: tf
      run: terraform apply -var-file=region.us-west-1.tfvars -auto-approve

    - name: Write private SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa


    - name: Wait for EC2 to be ready
      run: |
        IP=$(aws ec2 describe-instances \
          --region us-west-1 \
          --filters "Name=tag:Name,Values=natalie-control-plane" "Name=instance-state-name,Values=running" \
          --query "Reservations[0].Instances[0].PublicIpAddress" \
          --output text)

        echo "Checking SSH connection to $IP ..."
        for i in {1..10}; do
          if ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$IP "echo 'Instance is up'" ; then
            echo "✅ EC2 instance is reachable."
            break
          else
            echo "Waiting for instance to be ready..."
            sleep 10
          fi
        done

    - name: Save Terraform Output to file
      working-directory: tf
      run: |
        terraform output -raw control_plane_public_ip > control_plane_ip.txt